import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import schedulingImage from '../public/images/scheduling.png'


export default function Calendar() {
    return (
      <div className={styles.container}>
        <Head>
          <title>DPEasy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>

        <div className={styles.largeText} style={{marginTop:"5vh"}} id="calendar">
          <h1 style={{textAlign: "center"}} className={styles.title}>Calendar Integrations</h1>
          <p>Custom calendar solution for scheduling with applicants.</p>
          <h4>Features:</h4>
          <ul>
            <li >No more "I'll get back to you...'s</li>
            <li>Automatically schedule and sort applicants</li>
            <li>Automatically collect deposits</li>
            <li>Enforce 24-72 hour cancellation policies</li>
          </ul>

          <div style={{width:"80vw"}}>
            <Image
              src={schedulingImage}
              alt="Scheduling"
              
            />

          </div>
          
        </div>
        </main>
      </div>
    )
}