import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Demo.module.css'
import Link from 'next/link'
import { Calendly } from '../components/calendly'





export default function Demo() {
  return (
    <div className={styles.container}>
      <Head>
        <title>John Doe, DPE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      
        <h1 className={styles.title}>
          John Doe, DPE, CFII/MEI
        </h1>
        <h3 className={styles.code}>Experienced Daytona Beach, FL DPE</h3>


        <div className={styles.landing}></div>
        <p className={styles.description}>
          Get started by browsing our services below.
          
        </p>

       
        <Calendly></Calendly>

        <div className={styles.largeText} style={{marginTop:"5vh"}} id="pricing">
          <h1 style={{textAlign: "center"}} className={styles.title}>Pricing</h1>
          <p>Simple, transparent pricing.</p>


          
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
