import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          DPEasy
        </h1>
        <h3 className={styles.code}>The <em>headache-free</em> DPE scheduling and aquisition platform!</h3>


        <div className={styles.landing}></div>
        <p className={styles.description}>
          Get started by browsing our services below.
          
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Calendar + Scheduling &rarr;</h2>
            <p>Learn about what we can set up for your schedule.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Billing &rarr;</h2>
            <p>Want to collect deposits? Enforce 24 hour cancellations? Learn more.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Demo &rarr;</h2>
            <p>Check out a demo - see what we can create for your business.</p>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
