
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


import paymentImage from '../public/images/payment.png'

export default function Navbar() {
    return (
        
        <main className={styles.main}>
            <div className={styles.largeText} style={{marginTop:"5vh"}} id="billing">
                <Head>
                    <title>Payments</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
            <h1 style={{textAlign: "center"}} className={styles.title}>Billing Integrations</h1>
            <p>Checkride Billing, simplified.</p>
            <h4>Features:</h4>
            <ul>
                <li >Automated deposit collection</li>
                <li>Prevent chargebacks</li>
                <li>Low fees, collect payments on day of checkride</li>
                <li>Enforce 24-72 hour cancellation policies</li>
            </ul>

            <div style={{width:"80vw"}} className={styles.secondary}>
                <Image
                src={paymentImage}
                alt="Payment"
                
                
                />

            </div>
            
            </div>
        </main>
    )
}