import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import paymentsImage from '../public/images/payment.png'


export default function Payments() {
    return (
      <div className={styles.container}>
        <Head>
          <title>DPE Manager</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main className={styles.main}>

        <div className={styles.largeText} style={{marginTop:"5vh"}} id="payments">
          <h1 style={{textAlign: "center"}} className={styles.title}>Payment Integrations</h1>
          <p>Custom payments solution for processing applicant payments.</p>
          <h4>Features:</h4>
          <ul>
            <li >Automatic cancellation policy enforcement</li>
            <li>Detailed reporting and accounting</li>
            <li>Utilizing Stripe - Industry Standard</li>
          </ul>

          <div>
            <Image 
              style={{width: "80vw"}}
              src={paymentsImage}
              alt="Scheduling"
              
            />

          </div>
          
        </div>
        </main>
      </div>
    )
}